"""Init

Revision ID: 80e9d7ac828f
Revises: 20f6119f18c2
Create Date: 2023-03-28 13:01:46.965632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e9d7ac828f'
down_revision = '20f6119f18c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(length=150), nullable=False))
    op.drop_column('groups', 'group_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###
