"""Init

Revision ID: 9f587271fc0c
Revises: 72408a4d2999
Create Date: 2023-03-28 13:05:06.817593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f587271fc0c'
down_revision = '72408a4d2999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_of', sa.DateTime(), nullable=True))
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'date_of')
    # ### end Alembic commands ###
